newPRWelcomeComment: >
  Thank you and congratsðŸŽ‰ for opening this pull request!ðŸ’–


  Please make sure you have followed our [Contributing Guidelines](https://github.com/HITK-TECH-Community/Community-Website/blob/main/CONTRIBUTING.md).ðŸ™Œ
  We will test out your code and reply in a bit with some pointers and requests.ðŸ’¿
  There may be some errors, **but don't worry!** We'll work through them with you! ðŸ‘ðŸŽ‰ðŸ˜„
  If you haven't filled the template out, Please do so!ðŸš€

  Feel free to join our [Slack Community](https://join.slack.com/t/hitkteckcommunity/shared_invite/zt-jgr1sd87-lhiXHO_x63Kt7h8VBxDaFw).ðŸ’– We have different channels for active discussions.âœ¨ Hope you have a great time there!ðŸ˜„

firstPRMergeComment: >
  Congrats on merging your first pull request! ðŸ™Œ ðŸŽ‰ âš¡ï¸
  Now that you've merged your first pull request, you're the perfect person to help someone else out with this challenging first step.ðŸ˜„ðŸ™Œ

  Feel free to join our [Slack Community](https://join.slack.com/t/hitkteckcommunity/shared_invite/zt-jgr1sd87-lhiXHO_x63Kt7h8VBxDaFw).ðŸ’– We have different channels for active discussions.âœ¨ Hope you have a great time there!ðŸ˜„


newIssueWelcomeComment: >
  Hello there!ðŸ‘‹ Welcome to the project!ðŸš€âš¡


  Thank you and congratsðŸŽ‰ for opening your very first issue in this project. Community-website aims to build a resource sharing platform in order to reduce the knowledge gap. Please adhere to our [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md).ðŸ™Œ
  If you have screenshots or a gif to share demonstrating the issue, that's really helpful!ðŸ“¸
  Please make sure not to start working on the issue, unless you get assigned to it.ðŸ˜„
   

  Feel free to join our [Slack Community](https://join.slack.com/t/hitkteckcommunity/shared_invite/zt-jgr1sd87-lhiXHO_x63Kt7h8VBxDaFw).ðŸ’– We have different channels for active discussions.âœ¨ Hope you have a great time there!ðŸ˜„
